### ISSUE TITLE
Timeout Error for outgoing https Requests for APIs taking longer time to execute

### ISSUE THREAD

**Issue by avnibansal1995** [keploy/keploy#1515] opened 2024-02-07 11:40 UTC
I am encountering an error while executing an outgoing HTTPS request made from within an API with keploy record command .  The API takes more than 15 seconds to execute and works find outside keploy .  

Keploy debug logs : 
🐰 Keploy: 2024-02-07T10:51:46Z 	ERROR	httpparser/httpparser.go:703	failed to read the response message from the destination server	{"error": "read tcp IP1:55156->IP2:443: i/o timeout"}
go.keploy.io/server/pkg/proxy/integrations/httpparser.encodeOutgoingHttp
	/app/pkg/proxy/integrations/httpparser/httpparser.go:703
go.keploy.io/server/pkg/proxy/integrations/httpparser.(*HttpParser).ProcessOutgoing
	/app/pkg/proxy/integrations/httpparser/httpparser.go:38
go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection
	/app/pkg/proxy/proxy.go:918
go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1
	/app/pkg/proxy/proxy.go:580
🐰 Keploy: 2024-02-07T10:51:46Z 	ERROR	httpparser/httpparser.go:40	failed to encode the http message into the yaml	{"error": "read tcp IP1:55156-> IP2:443: i/o timeout"}
go.keploy.io/server/pkg/proxy/integrations/httpparser.(*HttpParser).ProcessOutgoing
	/app/pkg/proxy/integrations/httpparser/httpparser.go:40
go.keploy.io/server/pkg/proxy.(*ProxySet).handleConnection
	/app/pkg/proxy/proxy.go:918
go.keploy.io/server/pkg/proxy.(*ProxySet).startProxy.func1
	/app/pkg/proxy/proxy.go:580

**Comment by slayerjain** [comment] 2024-02-07 11:48
@avnibansal1995 thanks for creating the issue. 

we need to make the timeout configurable to allow intercepting slow outgoing http requests.

**Comment by officialasishkumar** [comment] 2024-02-07 12:04
I would like to work on this

**Comment by slayerjain** [comment] 2024-02-07 12:45
@officialasishkumar please feel free to pick

**Comment by PranshuSrivastava** [comment] 2024-02-07 16:33
@avnibansal1995 it seems like there is a problem with the way that your application is sending responses back to Keploy. It's either abrupty closing the connection without any EOF or is taking too long to send a response. Can you verify if any of these is true? You can try running the application without Keploy to check the response time.

**Comment by slayerjain** [comment] 2024-02-07 16:46
@PranshuSrivastava the outgoing API call is slow and so we need add timeout for outgoing API calls.

**Comment by varun7singh** [comment] 2024-02-24 18:23
Hi @avnibansal1995 @slayerjain  i was unable to reproduce this error could you help me out here?
Thanks!!

**Closed** 2024-07-08 08:42 UTC
Labels: Good First Issue, Go, GSoC
