### ISSUE TITLE
[bug]: add correct version in sentry

### ISSUE THREAD

**Issue by charankamarapu** [keploy/keploy#1032] opened 2023-10-19 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently a hardcoded version is injected into telemetry . Need to inject correct keploy version

### Steps to reproduce

1. View telemetry events

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by EraKin575** [comment] 2023-10-20 04:05
Please assign this to me!

**Comment by AniketNS** [comment] 2023-11-10 06:36
Hey @charankamarapu, Can I work on this issue?

**Comment by PranshuSrivastava** [comment] 2023-11-10 08:42
Hey @AniketNS, this issue was urgent so it was assigned to me. Please check if the issue is not assigned to anyone before asking to work on it.

**Closed by PranshuSrivastava** 2023-11-10 08:42 UTC
Labels: bug, keploy

**Comment by AniketNS** [comment] 2023-11-10 09:19
Sure @PranshuSrivastava. Thanks for the advice.
