### ISSUE TITLE
[bug]: Accessing an empty test-report from the map when user app is not started

### ISSUE THREAD

**Issue by re-Tick** [keploy/keploy#1097] opened 2023-11-09 05:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When the user application is unable to start in the test mode. Then the following error is thrown:
```
🐰 Keploy:%!(EXTRA string=found no test results for test report with id: %v, string=report-3)

/app/pkg/service/test/test.go in go.keploy.io/server/pkg/service/test.(*tester).RunTestSet at line 417
In App
/app/pkg/service/test/test.go in go.keploy.io/server/pkg/service/test.(*tester).Test at line 161
In App
/app/cmd/test.go in go.keploy.io/server/cmd.(*Test).GetCmd.func1 at line 219
In App
Called from: /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go in (*Command).execute

Show 2 more frames
/app/cmd/root.go in go.keploy.io/server/cmd.(*Root).execute at line 218
In App
/app/cmd/root.go in go.keploy.io/server/cmd.Execute at line 142
In App
/app/main.go in main at line 51
```

### Steps to reproduce

1. Record some test cases for your application.
2. Then start the API server on same port in other terminal.
3. And run the application in test mode.

### Environment

None

### Version

Local

### Repository

keploy

**Comment by nakulbh** [comment] 2023-11-09 14:52
@charankamarapu can you assign this issue to me so that i can work on it

**Comment by charankamarapu** [comment] 2023-11-09 14:54
sure @nakulbh

**Comment by nakulbh** [comment] 2023-11-10 19:34
@re-Tick can you help me reproduce the error

**Comment by re-Tick** [comment] 2023-11-21 13:26
Hi @nakulbh, the error log is posted on the sentry. So, the steps/environment in which the logs are not known. But the issue could be because of the accessing the GetResults which are not set in the for loop of runTestSet. [Here](https://github.com/keploy/keploy/blob/68c528fd2462490c5f5940e06c6f8565bb93fb17/pkg/platform/yaml/testReport.go#L46) the returned error can be ignored if no testcase has called for SetResult in the loop.

**Comment by gouravkrosx** [comment] 2024-06-27 07:55
Unable to reproduce this issue after v2-refactoring.

**Closed by gouravkrosx** 2024-06-27 07:55 UTC
Labels: bug, keploy
