### ISSUE TITLE
[bug]: docker compose up needs containers to be removed

### ISSUE THREAD

**Issue by PranshuSrivastava** [keploy/keploy#1533] opened 2024-02-08 11:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When you try to start an application with its docker compose file with Keploy, and some other process is running on the port that one of the services is intended to run, an error is logged and Keploy stops. But even when we kill the process on that port and restart the services using docker compose, Keploy fails to find the mentioned container even though it has started. To fix this we have to remove all the containers mentioned in the docker compose file and then run with Keploy again.

This behaviour is not expected and Keploy should automatically handle this without us needing to remove  the containers manually. You can replicate this bug with the gin-mongo application in the samples-go repository of Keploy.

When I start the application, with Keploy when mongoDb is already running on port 27017:
<img width="1440" alt="image" src="https://github.com/keploy/keploy/assets/37413698/c2ad71b7-77c5-4158-b91a-2e99f7450f0b">

When i stop mongodb and try to run the application with Keploy again:
<img width="1440" alt="image" src="https://github.com/keploy/keploy/assets/37413698/f681673c-308a-47dc-9ee7-68fddf990720">

As you can see the application has already started but Keploy is not able to process the container.
To fix this we need to remove both the containers mentioned in the docker compose file of the project and then start the application with Keploy again.

### Steps to reproduce

1. Start any server on port 8080
2. Try to start any service that runs on port 8080 with docker compose file with Keploy.
3. Once Keploy fails to start the application, kill the process, and try to start the services again.
4. The service should get started successfully but Keploy will still log that it is unable to find the required container and stop eventually.

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Yaxhveer** [comment] 2024-02-12 18:11
Working on this.

**Comment by Yaxhveer** [comment] 2024-02-25 17:59
This happens because in initial case when containers are created and started port allocation error occurs and the container is stopped. When we again try the keploy docker compose up command the previously created container are started emitting the start event but not the create event. Since keploy only listens for create event does not finds the container in the latter case. So I have raised a PR  for the same please review and let me know if it works #1596.

**Comment by Yaxhveer** [comment] 2024-04-04 22:19
Hey @PranshuSrivastava , I was trying to reproduce this issue with gin-mongo app to update my pending PR, but the execution of keploy was blocked after showing ```error while running the app``` log and on pressing ctrl+c it paniced. 
<img width="698" alt="image" src="https://github.com/keploy/keploy/assets/101015836/d61704c4-2f01-4e81-a10e-03939517cd51">
So wanted to confirm is this issue known or not. 
Also, know the containers are not being removed by keploy if they are created using docker compose.

**Comment by gouravkrosx** [comment] 2024-10-08 06:34
Closing this issue as it was solved during refactoring, Feel free to open the issue if it still happens.

**Closed by gouravkrosx** 2024-10-08 06:34 UTC
Labels: bug, GSoC, keploy
