### ISSUE TITLE
[bug]: the logo of the twitter is not updated 

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [keploy/keploy#977] opened 2023-10-06 16:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The logo of the twitter is not updated .

### Steps to reproduce

-Go to the website home page
-Scroll down 
-See the twitter logo
-see the logo of the twitter is not updated

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by pranxv** [comment] 2023-10-07 05:14
Hey, can I work on updating this ?

**Comment by Tanisha-b3** [comment] 2023-10-07 07:14
hey can I work on this?

**Comment by PranshuSrivastava** [comment] 2023-10-09 07:21
Hey @pranxv, are you still interested in working on this? @Tanisha-b3, we allot issues on first come first serve basis, if @pranxv doesn't take up this issue, it will be assigned to you.

**Comment by PranshuSrivastava** [comment] 2023-10-11 12:13
Since the other contributors are not responding, you can go ahead and work on this @Aayushi-Agrwal.

**Comment by Aayushi-Agrwal** [comment] 2023-10-11 12:53
just confirming, the repo is https://github.com/keploy/website ?

**Comment by Sha1kh4** [comment] 2023-10-12 15:09
@PranshuSrivastava as can you assign me this?

**Comment by PranshuSrivastava** [comment] 2023-10-12 19:46
> just confirming, the repo is https://github.com/keploy/website ?
> 

Yup

**Comment by PranshuSrivastava** [comment] 2023-10-12 19:48
> @PranshuSrivastava as can you assign me this?
> 

Sorry, but since someone is already working on this, I cannot assign this issue to you. Please look for some other issues that you can help with. You can find them under the hacktoberfest-2023 tag.

**Comment by Aayushi-Agrwal** [comment] 2023-10-14 06:24
How do I open a PR. That repo is read only? @PranshuSrivastava

**Comment by PranshuSrivastava** [comment] 2023-10-16 08:03
@Aayushi-Agrwal You need to create your own fork of Keploy and then create a new branch in your fork and add your changes there. After your changes have been confirmed, push them to your fork and then open a PR from your forked:branch to keploy:main

**Comment by 9520prashant** [comment] 2023-10-19 09:35
Hey @PranshuSrivastava It's been 1 week but issue is still open can you please confirm that is that resolve if no please assign me this issue.

**Comment by SUNIDHI-JAIN125** [comment] 2024-01-03 12:42
Hey @9520prashant Are you still woking on this issue, it's still not fixed. 
If not then I would like to merge a PR.
I guess these are the major places where the icon should be changed.
![Screenshot from 2024-01-03 18-11-11](https://github.com/keploy/keploy/assets/130484301/dbf1370e-dd69-472a-9c03-73c47266d083)
![Screenshot from 2024-01-03 18-11-50](https://github.com/keploy/keploy/assets/130484301/68372e78-09ba-4093-8afb-e8a8f4188e37)

**Comment by 9520prashant** [comment] 2024-01-03 12:45
> Hey @9520prashant Are you still woking on this issue, it's still not fixed. If not then I would like to merge a PR. I guess these are the major places where the icon should be changed. ![Screenshot from 2024-01-03 18-11-11](https://private-user-images.githubusercontent.com/130484301/293915590-dbf1370e-dd69-472a-9c03-73c47266d083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODYxNzgsIm5iZiI6MTcwNDI4NTg3OCwicGF0aCI6Ii8xMzA0ODQzMDEvMjkzOTE1NTkwLWRiZjEzNzBlLWRkNjktNDcyYS05YzAzLTczYzQ3MjY2ZDA4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMjQ0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWE0YTY2Njg4Y2RmYzIxNTMyMTA5YTBjZmMyMGYwNzY1YTY5MDgwYmVjYjdkMjRhOTZmYWEzOTY1ODQyOGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L4r8oVJfKJOv8800H-MEDxLC-kPpDdvgdB2Ju-hCwyo) ![Screenshot from 2024-01-03 18-11-50](https://private-user-images.githubusercontent.com/130484301/293915612-68372e78-09ba-4093-8afb-e8a8f4188e37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODYxNzgsIm5iZiI6MTcwNDI4NTg3OCwicGF0aCI6Ii8xMzA0ODQzMDEvMjkzOTE1NjEyLTY4MzcyZTc4LTA5YmEtNDA5My04YWZiLWU4YThmNDE4OGUzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMjQ0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2VmZGQzZjZkODUwZDA5MzFjODIwOGM0OGExNzI0ZDg3MmJhMjFiNWJiYWI0ZDk1ZGY5NTZhNjdhMDdhMTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5zHfKAkPMdqN9YlY17ta7bSF9B39hAw_XjyzUkuSlHI)

Hey Sunidhi You can work on it.

**Comment by SUNIDHI-JAIN125** [comment] 2024-01-05 04:36
I am working on this. Assign me this issue please.

**Comment by SUNIDHI-JAIN125** [comment] 2024-01-13 16:15
Hey!! @PranshuSrivastava  Can you please assign me this issue.

**Comment by nehagup** [comment] 2024-01-14 06:01
@SUNIDHI-JAIN125 please feel free to make a PR.

**Comment by SUNIDHI-JAIN125** [comment] 2024-01-17 09:26
@nehagup Ma'am I have already raised the PR in Keploy Docs Repo.
If possible please review it. However I couldn't change twitter icon in  official website https://keploy.io/ as it is not open source.
https://github.com/keploy/docs/pull/306

Before Changes
![Screenshot from 2024-01-17 14-33-23](https://github.com/keploy/keploy/assets/130484301/4d139bcd-bfc9-4ba4-ac64-fc1d74ee2bcf)


After Changes 
![Screenshot from 2024-01-17 11-36-59](https://github.com/keploy/keploy/assets/130484301/8ec98ac1-7d99-4d45-a180-4563721ed96c)

**Comment by nehagup** [comment] 2024-01-31 12:28
@SUNIDHI-JAIN125 thanks for the PR, merged it ! :)

**Closed by nehagup** 2024-01-31 12:28 UTC
Labels: bug, keploy

**Comment by SUNIDHI-JAIN125** [comment] 2024-02-01 02:14
Thanks a lot! @nehagup Ma'am
