### ISSUE TITLE
[feature]: add validation to dependency request data

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#433] opened 2023-03-04 15:51 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

It would be very useful to also have validation in the dependency calls. This should be configured to allow the user to chose whether to consider discrepancies in dependency calls as errors or just a warning. 

### Why should this be worked on?

Keploy currently only checks for the response of the APIs. It would be great to also have validation on downstream requests such as external API, DB calls, etc. This would enable the user to better assert the behaviour of applications.

**Comment by nehagup** [comment] 2023-03-04 16:15
@slayerjain This seems duplicate of #26

**Comment by charankamarapu** [comment] 2023-12-05 18:52
This has been taken care in keploy v2.

**Closed by charankamarapu** 2023-12-05 18:52 UTC
Labels: Enhancement
