### ISSUE TITLE
[test]: Testing Keploy Hosted with Recent Updates in Keploy 

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/keploy#1372] opened 2024-01-15 19:49 UTC
- We need to test both the conditions locally before adding it to the keploy test-bench pipeline.
    - `keployR(hosted) -c keployT(build) -c "app"`
    - `keployR(build) -c keployT(hosted) -c "app"`

**Comment by slayerjain** [comment] 2024-01-23 16:36
duplicate of https://github.com/orgs/keploy/projects/4/views/6?pane=issue&itemId=50045171

**Closed** 2024-01-23 16:37 UTC
