### ISSUE TITLE
[feature]: Add Keploy arm64 formula on homebrew 

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1385] opened 2024-01-17 08:01 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Need to add arm64 formula in Homebrew for Apple silicon support. 

### Why should this be worked on?

Apple silicon is the new default for macOS. 

### Repository

keploy

**Comment by PranshuSrivastava** [comment] 2024-01-29 12:55
Currently blocked because of [this](https://github.com/orgs/Homebrew/discussions/5085#discussioncomment-8242420)

**Comment by Swpn0neel** [comment] 2024-07-08 09:18
Does this issue still persist @slayerjain ?

**Comment by karahmon** [comment] 2024-07-17 06:19
@Swpn0neel would love to work on the issue and get it done asap, kindly assign it to me

**Comment by karahmon** [comment] 2024-07-17 06:28
I think @Swpn0neel @Sonichigo the issue is already resolved, kindly check once https://formulae.brew.sh/formula/keploy#default
https://github.com/Homebrew/homebrew-core/blob/2982c2810a94ce62de807c4f2c5f677c8b4dfc32/Formula/k/keploy.rb

can see it is already supported

**Comment by Sonichigo** [comment] 2024-07-17 06:40
@karahmon that's an old version of keploy that is present in homebrew :- https://github.com/orgs/Homebrew/discussions/5085#discussioncomment-8242420

**Comment by karahmon** [comment] 2024-07-18 06:03
@Sonichigo have raised a pull request on homebrew repository, but CI / tap_syntax (pull_request) keeps failing as all versions contain the term alpha which as pranshu had mentioned earlier only stable versions without the url having terms alpha/beta without it, i had gone through all the versions after v0.9.1 all contain alpha therefore tests  CI / tap_syntax (pull_request) required by them keeps failing, will try to check with their reviewers if anything can be done about it
https://github.com/Homebrew/homebrew-core/pull/177685

**Comment by Sonichigo** [comment] 2024-07-22 13:13
> @Sonichigo have raised a pull request on homebrew repository, but CI / tap_syntax (pull_request) keeps failing as all versions contain the term alpha which as pranshu had mentioned earlier only stable versions without the url having terms alpha/beta without it, i had gone through all the versions after v0.9.1 all contain alpha therefore tests CI / tap_syntax (pull_request) required by them keeps failing, will try to check with their reviewers if anything can be done about it [Homebrew/homebrew-core#177685](https://github.com/Homebrew/homebrew-core/pull/177685)

I think till the stable version is released, this issue would be on stale since based on your research we can conclude that not much can be done right now.

**Closed by Sonichigo** 2024-07-22 13:13 UTC
Labels: Enhancement, keploy, kROC, level-2
