### ISSUE TITLE
[bug]: tar: Cannot open: File exists

### ISSUE THREAD

**Issue by Sonichigo** [keploy/keploy#1949] opened 2024-06-10 06:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While trying to install keploy via one-click, i got the below error message, similar thing happened while i was trying to install in jenkins pipeline as well.

<img width="931" alt="image" src="https://github.com/keploy/keploy/assets/53110238/0ace8e14-0437-4fff-bfae-3473688ea2d4">

I previously solved this via adding `--overwrite` in tar command.

### Steps to reproduce

1. Install keploy wit one-click
2. Warn message would show up just before keploy examples show's up. 

### Environment

None

### Version

Local

### Repository

keploy

**Comment by Sonichigo** [comment] 2024-06-19 09:21
<img width="1065" alt="image" src="https://github.com/keploy/keploy/assets/53110238/219b49e1-fd76-4e5d-9cc5-c40f2c0cad1f">

The Issue still persists in alpha8 with one-click

**Comment by besasch88** [comment] 2024-06-26 20:33
@Sonichigo I'm not able to reproduce it. A possible issue could be caused by previous script execution that has been interrupted before moving the extracted folder in the `bin` folder (very edge case).

```
curl --silent --location "$download_url" | tar xz -C /tmp
sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploybin
```

In any case, if you agree, we can force the script to delete the keploy folder if exists before downloading the package. What do you think? If ok, I can open a PR for that.

**Comment by besasch88** [comment] 2024-06-26 21:43
@Sonichigo Hi, which OS are you using? 

Your issue seems related to a wrong permissions config of the `tmp` folder because the script execute the `cURL` and `tar` extraction without `sudo` permissions:
`curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_darwin_all.tar.gz" | tar xz -C /tmp`

Seems you are able to workaround it adding the `--overwrite`  parameter in tar command because, with this parameter, tar does not try to delete the file and re-create it with the new extracted one, but, instead, is opening the file and replace its content.  You can verify it by executing `ls -ali` in your folder, you will notice that the Node ID does not change with the `--overwrite` parameter applied ;) 

BTW I don't think the issue is related to Keploy project itself. But, if we want, we can force the usage of `sudo` also for `cURL` and `tar` commands ;) 

I suggest to take a look to your folder and file permissions and ensure there are not protection on deleting the file (theoretically on Linux and Mac, there isn't this option)

**Comment by Sonichigo** [comment] 2024-06-27 07:36
> @Sonichigo Hi, which OS are you using?
> 
> Your issue seems related to a wrong permissions config of the `tmp` folder because the script execute the `cURL` and `tar` extraction without `sudo` permissions: `curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_darwin_all.tar.gz" | tar xz -C /tmp`
> 
> Seems you are able to workaround it adding the `--overwrite` parameter in tar command because, with this parameter, tar does not try to delete the file and re-create it with the new extracted one, but, instead, is opening the file and replace its content. You can verify it by executing `ls -ali` in your folder, you will notice that the Node ID does not change with the `--overwrite` parameter applied ;)
> 
> BTW I don't think the issue is related to Keploy project itself. But, if we want, we can force the usage of `sudo` also for `cURL` and `tar` commands ;)
> 
> I suggest to take a look to your folder and file permissions and ensure there are not protection on deleting the file (theoretically on Linux and Mac, there isn't this option)

Hey @besasch88 ! I'm using Debian and Mac. And was able to replicate the issue on few CI/CD as well such as Jenkins.
```sh
[Pipeline] sh
+ curl --silent --location https://github.com/keploy/keploy/releases/latest/download/keploy_linux_arm64.tar.gz
+ tar xz -C /tmp
tar: LICENSE: Cannot open: File exists
tar: README.md: Cannot open: File exists
tar: READMEes-Es.md: Cannot open: File exists
tar: keploy: Cannot open: File exists
tar: Exiting with failure status due to previous errors
[Pipeline] }
[Pipeline] // stage
```

I agree that the error isn't related to Keploy project but rather with the installation setup.

**Comment by besasch88** [comment] 2024-06-28 10:47
@Sonichigo Sorry,  I tried to understand what is going on, but without being able to reproduce the issue is quite hard. 

If you can share few information could be useful to try to replicate the same behaviour:

- current permission sets of these files, maybe with: `ls -al` in the `tmp` folder (feel free to exclude files that are not relevant)
- the output of `tar --version`
- the output of `uname -a`.

Thanks!

**Comment by Sonichigo** [comment] 2024-06-28 12:02
<img width="1025" alt="image" src="https://github.com/keploy/keploy/assets/53110238/a185dc13-3cec-4905-866d-4cff19373752">

Did ran the curl command for the latest alpha16 release same thing.

tar -version :- 
```
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

uname -a : - `Linux lima-default 6.1.0-21-cloud-arm64 #1 SMP Debian 6.1.90-1 (2024-05-03) aarch64 GNU/Linux`

<img width="667" alt="image" src="https://github.com/keploy/keploy/assets/53110238/8bc46d99-a8b7-4ef2-b574-0f20c69c829c">

**Comment by suvanbanerjee** [comment] 2024-07-15 15:57
@Swpn0neel A few questions
1. How to replicate this issue (tried this installer script on my system and didn't get this issue)
2.  I think sudo is already forced?
 > BTW I don't think the issue is related to Keploy project itself. But, if we want, we can force the usage of `sudo` also for `cURL` and `tar` commands ;) 
3. Silly doubt but where is the location of installer.sh

**Comment by Swpn0neel** [comment] 2024-07-15 18:11
> @Swpn0neel A few questions
> 
> 1. How to replicate this issue (tried this installer script on my system and didn't get this issue)
> 2. I think sudo is already forced?
> 
> > BTW I don't think the issue is related to Keploy project itself. But, if we want, we can force the usage of `sudo` also for `cURL` and `tar` commands ;)
> 
> 3. Silly doubt but where is the location of installer.sh

@Sonichigo Kindly help him!

**Comment by Sonichigo** [comment] 2024-07-16 05:50
> @Swpn0neel A few questions
> 
> 1. How to replicate this issue (tried this installer script on my system and didn't get this issue)
> 2. I think sudo is already forced?
> 
> > BTW I don't think the issue is related to Keploy project itself. But, if we want, we can force the usage of `sudo` also for `cURL` and `tar` commands ;)
> 
> 3. Silly doubt but where is the location of installer.sh

1. The issue comes up in certain scenarios and randomly. You can replicate the issue directly on jenkins,it's consistently present there. 

2. Sudo is enforced for commands only which require sudo access. with cURL or tar it isn't needed. a simple flag of `--overwrite` can fix the issue which arises after installing keploy for the second time.

3. https://github.com/keploy/keploy/blob/main/keploy.sh

**Comment by suvanbanerjee** [comment] 2024-07-16 06:20
@Sonichigo Thanks for clarification i thing forcing sudo and then testing script will do the job, I would like to solve this issue please assign it to me.

**Comment by Swpn0neel** [comment] 2024-07-16 07:03
Go ahead @suvanbanerjee But you won't get assigned to further issues, until you make PRs for the already assigned ones 😊!!

**Closed** 2024-08-05 13:37 UTC
Labels: bug, keploy, kROC, level-2
