### ISSUE TITLE
[bug]: JSON array diff not specific enough

### ISSUE THREAD

**Issue by slayerjain** [keploy/keploy#1496] opened 2024-02-05 08:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently is there is a diff in a JSON array, keploy would highlight the entire string after the faulty string. This makes it hard to see the diff. Eg: 

<img width="874" alt="Screenshot 2024-02-05 at 1 38 46 PM" src="https://github.com/keploy/keploy/assets/12831254/cd1e3ffd-0dc5-4a1f-a5bc-45adcb947fa9">

It should only highlight the difference and leave the rest. The potential reason could be that the JSON array diff compare is not implemented for JSON Array type or there is incorrect matching of type. 

### Steps to reproduce

1. Create an application which returns a JSON Array. 
2. Record test cases.
3. Change a field from any of the object from the array. 
4. Non diff items will also be highlighted (as above)

### Environment

None

### Version

Cloud

### Repository

keploy

**Comment by Akash-Singh04** [comment] 2024-02-05 10:17
Hey there! I would like to try fixing this.

**Comment by slayerjain** [comment] 2024-02-05 12:22
@shivamsouravjha please review this once there is a PR.

**Comment by Akash-Singh04** [comment] 2024-02-06 18:55
@slayerjain Could you provide the exact application in which the jsonarr diff are not visible. It would make it easier for me to develop a solution if you could provide it. Thanks

**Comment by shivamsouravjha** [comment] 2024-02-13 09:05
Hey @Akash-Singh04 in `calculateJSONDiffs` the `Format` function does have formatArray and formatObject. 


Can you please explain the error in detail.

**Comment by Akash-Singh04** [comment] 2024-02-13 12:25
I am referring to these two functions

![image](https://github.com/keploy/keploy/assets/114267538/d426b186-d81a-4021-a3ca-43146e2f2396)

![image](https://github.com/keploy/keploy/assets/114267538/a731aae6-88a6-46e5-87db-559a25e308f0)

The ```separateAndColourize``` function is documented to only work with Json

![image](https://github.com/keploy/keploy/assets/114267538/1064e883-9e22-4a76-b333-a071700b37b6)

The function ```sprintJSONDiff``` which calls ```calculateJSONDiffs``` and ```separateaAndColourize``` is also documented to only work with JSONS

Hence, when an array of Jsons is passed, ```sprintDiff``` is called instead
![image](https://github.com/keploy/keploy/assets/114267538/7b45868d-0eca-4679-a330-9c8f46815627)


This according to me is the cause of the problem.

**Comment by shivamsouravjha** [comment] 2024-02-13 12:47
Agreed this seems to be the problem with the `calculateJSONDiffs` as it throws error on diff.Compare.

The dependency seems to be inactive for a while and thus we're looking for alternatives as well.

<img width="626" alt="image" src="https://github.com/keploy/keploy/assets/60891544/87e4810c-6295-4c4a-95d5-5466dcb66c3b">

**Comment by Akash-Singh04** [comment] 2024-02-13 18:56
Alright, let me know what is the alternative approach to this. Had a lot of fun learning and debugging this!

**Comment by Akash-Singh04** [comment] 2024-05-03 19:14
Since we switched to GJSON from gojsondiff, this issue was resolved and can be closed @slayerjain

**Comment by shivamsouravjha** [comment] 2024-07-05 16:06
this has been linked in another issue thus closing the same.

**Closed by shivamsouravjha** 2024-07-05 16:06 UTC
Labels: bug, keploy
