### ISSUE TITLE
[feature]: Improve Existing Twitter Reviews 

### ISSUE THREAD

**Issue by TvisharajiK** [keploy/keploy#2386] opened 2024-10-28 11:00 UTC
### 👀 Is there an existing feature request for this?

- [X] I have searched the existing issues

### 🔖 Enhancement description

[](url)
<img width="1440" alt="Screenshot 2024-10-28 at 4 07 07 PM" src="https://github.com/user-attachments/assets/79846d2f-326d-47ab-910a-6d4bde80f2ed">

Change this to a moving carousel like this (open to your creativity)
<img width="712" alt="Screenshot 2024-10-28 at 4 29 44 PM" src="https://github.com/user-attachments/assets/8f7f060e-8876-4a33-aa89-43bd418fef16">

https://shapo.io/blog/embed-free-twitter-testimonials-and-reviews-widget/

### 🎤 Why should this be worked on?

Twitter review carousel

### 💻 Repository

keploy

**Comment by Aviral0702** [comment] 2024-10-28 12:10
@TvisharajiK I can take up this issue.

**Comment by wasifkareem** [comment] 2024-10-28 12:49
Hi @Aviral0702  you already have an issue assigned, @TvisharajiK can I please take this one?

**Comment by prabhat135** [comment] 2024-10-28 13:00
Hello @TvisharajiK, I have started working on this issue. Please assign it to me!

**Comment by DhairyaMajmudar** [comment] 2024-10-28 14:23
Hi @wasifkareem @TvisharajiK can you pls. assign the issue to me

**Comment by Sonichigo** [comment] 2024-10-29 05:35
Hi @DhairyaMajmudar the issue is taken by @prabhat135 !

**Comment by TusharTemgire** [comment] 2024-10-29 17:24
I can take up this issue.

**Comment by AbhishekTemgire** [comment] 2024-10-29 17:26
@TvisharajiK please assign this issues to @TusharTemgire

**Comment by TvisharajiK** [comment] 2024-10-29 17:59
@prabhat135 if you are not working on this issue @TusharTemgire can take it up
Let me know

**Comment by TvisharajiK** [comment] 2024-10-30 07:47
@DhairyaMajmudar @TusharTemgire @prabhat135 

We’re currently reviewing and merging PRs on a first-come, first-served basis, while also considering which PRs best fit the use case. If you’d like to contribute, please feel free to work on it at your convenience!

**Comment by TusharTemgire** [comment] 2024-10-30 07:58
@TvisharajiK could you please assign me issue

**Comment by TvisharajiK** [comment] 2024-10-30 08:00
@TusharTemgire We cannot assign the issues, post merging it will be done. Reiterating the previous comment

**Comment by prabhat135** [comment] 2024-10-30 13:56
@TvisharajiK I am working on it and will submit the PR asap.

**Comment by 29deepanshutyagi** [comment] 2024-10-30 16:27
i want to work on this issue ,if it's still open ,kindly assign me @TusharTemgire

**Comment by gurshaan17** [comment] 2024-10-30 20:21
https://github.com/user-attachments/assets/ebd3a1e9-3953-4ddc-8368-632842bd0007

One more row of tweets can be added if you want 
@TvisharajiK

**Comment by Nikhilh26** [comment] 2024-10-31 11:53
[https://github.com/keploy/website/pull/119](url)
I have raised the PR

**Comment by vinod95990** [comment] 2024-10-31 17:43
https://github.com/keploy/website/pull/121
I've implemented a solution for this issue in the UI repository. The pull request includes a new 3-row animated layout for Twitter reviews. Let me know if there's any feedback or additional adjustments needed!

**Comment by vivekchavan14** [comment] 2024-11-01 08:36
I've raised a PR, can u please review it

**Comment by kotesh-arya** [comment] 2024-11-01 09:47
Raised a Detailed [PR](https://github.com/keploy/website/pull/122) with necessary changes and a considering a best practice, Would love to hear from you @TvisharajiK

**Closed** 2024-11-04 12:17 UTC
Labels: Enhancement, Good First Issue, keploy
